### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by AImagicAI** [KyanChen/RSPrompter#102]
你好，运行lightning版本，报错信息如下：
`Traceback (most recent call last):
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/train.py", line 47, in <module>
    main()
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/train.py", line 43, in main
    runner.run(args.status, ckpt_path=args.ckpt_path)
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/../mmpl/engine/runner/pl_runner.py", line 321, in run
    return trainer_func(model=self.model, datamodule=self.datamodule, *args, **kwargs)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 896, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 81, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 162, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/../mmpl/datasets/pl_datamodule.py", line 42, in setup
    self.train_dataset = build_dataset(dataset_cfg)
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/../mmpl/datasets/builder.py", line 25, in build_dataset
    return DATASETS.build(cfg)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/../mmdet/datasets/base_det_dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/home/cv8888/byf/industrial_vision/SAM/RSPrompter_lightning/tools/../mmdet/datasets/base_det_dataset.py", line 78, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/home/cv8888/anaconda3/envs/python310/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 768, in _serialize_data
    data_bytes = np.concatenate(data_list)
ValueError: need at least one array to concatenate
`

**Comment by KyanChen** [comment]
请更换新版本
