### ISSUE TITLE
想问为什么一直没安装好包 就反反复复一直提示什么什么不行 但是到torchvision再也修复不了了

### ISSUE THREAD

**Issue by Sophia-924** [KyanChen/RSPrompter#68]
(RSPrompter) C:\Users\admin>python RSPrompter-cky/tools/train.py
Traceback (most recent call last):
  File "C:\Users\admin\RSPrompter-cky\tools\train.py", line 7, in <module>
    from mmpl.engine.runner import PLRunner
  File "C:\Users\admin\RSPrompter-cky\tools/..\mmpl\engine\__init__.py", line 1, in <module>
    from .runner import *
  File "C:\Users\admin\RSPrompter-cky\tools/..\mmpl\engine\runner\__init__.py", line 1, in <module>
    from .pl_runner import PLRunner
  File "C:\Users\admin\RSPrompter-cky\tools/..\mmpl\engine\runner\pl_runner.py", line 15, in <module>
    from lightning.pytorch.loggers import Logger
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\lightning\__init__.py", line 27, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\lightning\pytorch\__init__.py", line 26, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\lightning\pytorch\callbacks\__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\lightning\pytorch\callbacks\batch_size_finder.py", line 24, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\lightning\pytorch\callbacks\callback.py", line 25, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\lightning\pytorch\utilities\types.py", line 25, in <module>
    from torchmetrics import Metric
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\torchmetrics\functional\__init__.py", line 49, in <module>
    from torchmetrics.functional.detection._deprecated import _panoptic_quality as panoptic_quality
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\torchmetrics\functional\detection\__init__.py", line 25, in <module>
    from torchmetrics.functional.detection.giou import generalized_intersection_over_union  # noqa: F401
  File "D:\Anaconda3\envs\RSPrompter\lib\site-packages\torchmetrics\functional\detection\giou.py", line 21, in <module>
    from torchvision.ops import generalized_box_iou
ModuleNotFoundError: No module named 'torchvision.ops'

**Comment by KyanChen** [comment]
可以尝试下行更新的版本
